name: Merged

on:
  pull_request:
    types: closed
    branches: master

env:
  STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  DEPLOY_GATE_TOKEN: ${{secrets.DEPLOY_GATE_TOKEN}}
  DEPLOY_GATE_USER_NAME: ${{secrets.DEPLOY_GATE_USER_NAME}}

jobs:
  build:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decrypt
        run: .github/scripts/decrypt_secret.sh
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
      - name: Build
        run: ./gradlew assembleDebug
      - name: Deploy to DeployGate
        run: .github/scripts/deploy_on_merged.sh
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
      - name: Slack notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_COLOR: '#00FF00'
          SLACK_TITLE: ':rocket::merge: Deploy(Merged) :merge::rocket:'
          SLACK_MESSAGE: "Deploy success!\nThis deploy is based on \"${{ env.DEPLOY_MESSAGE }}\"\n<${{ env.DISTRIBUTION_URL }} | Download link>"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEPLOY }}

  delete-distribution-page:
    runs-on: ubuntu-latest

    steps:
      - name: Delete Deploygate distribution page
        run: .github/scripts/delete_distribution_page.sh