name: Merged

on:
  pull_request:
    types: closed
    branches: master

env:
  STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

jobs:
  build:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decrypt
        run: .github/scripts/decrypt_secret.sh
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
      - name: Build
        run: ./gradlew assembleDebug
      - name: Deploy to DeployGate
        run: .github/scripts/deploy_on_merged.sh
